export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const LOADING = 'LOADING';
export const REGISTER = 'REGISTER';
export const LOGGEDIN = 'LOGGEDIN';
export const REGFORM ="REGFORM";
export const ERROR_LOGIN = "ERROR_LOGIN"
export const LOGOUT = "LOGOUT"
